set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]

set_property LOCK_PINS {I0:A5 I1:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/NAND_STAGE}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_1}]
set_property LOCK_PINS {I0:A6} [get_cells {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_2}]





