# ================================================================
# Frozen RO placement and routing
# Exact-name version generated from: impl_freeze_test
# ================================================================

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X41Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X41Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X41Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X41Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X41Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X41Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X41Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X41Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D5 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X46Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X46Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X46Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X46Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X44Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X44Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X44Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X44Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X47Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X47Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X47Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X47Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X41Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X41Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X41Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X41Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X46Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X46Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X46Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X46Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X46Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X46Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X46Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X46Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X44Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X44Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X44Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X44Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X47Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X47Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X47Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X47Y70 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X41Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X41Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X41Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X41Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X46Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X46Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X46Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X46Y69 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X44Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X44Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X44Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X44Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X47Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X47Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X47Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X47Y68 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X44Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X44Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X44Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X44Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property BEL SLICEL.B6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOC SLICE_X47Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_1"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property BEL SLICEL.C6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOC SLICE_X47Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]
set_property LOCK_PINS I0:A6 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_2"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property BEL SLICEL.A6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOC SLICE_X47Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]
set_property LOCK_PINS {I0:A5 I1:A6} [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/NAND_STAGE"}]

# PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/TAP_BUFFER
set_property BEL SLICEL.D6LUT [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOC SLICE_X47Y71 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_BEL_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property IS_LOC_FIXED TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property DONT_TOUCH TRUE [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]
set_property LOCK_PINS I0:D3 [get_cells -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/TAP_BUFFER"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E5 INT_NODE_IMUX_15_INT_OUT1 BYPASS_E8 INT_NODE_IMUX_4_INT_OUT1 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_1_INT_OUT0 INT_INT_SDQ_72_INT_OUT0 INT_NODE_GLOBAL_11_INT_OUT1 INT_NODE_IMUX_11_INT_OUT0  { IMUX_E18 }  BYPASS_E1 INT_NODE_IMUX_7_INT_OUT0 IMUX_E31 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/OSC_COMP/stage_0"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_1
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E20 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/stage_1"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/INV_STAGE_2
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_C_O INT_NODE_SDQ_3_INT_OUT1 INT_INT_SDQ_32_INT_OUT1 INT_NODE_SDQ_55_INT_OUT0 INT_INT_SDQ_4_INT_OUT0 INT_NODE_IMUX_1_INT_OUT1  { IMUX_E17 }  IMUX_E18 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/ro_feedback"}]

# Route driven by PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/NAND_STAGE
set_property FIXED_ROUTE { { CLE_CLE_L_SITE_0_A_O INT_NODE_IMUX_0_INT_OUT0 BOUNCE_E_2_FT1 INODE_E_58_FT0 IMUX_E19 }  } [get_nets -hier -quiet -filter {NAME == "PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/OSC_COMP/stage_0"}]

