
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys_clk_internal_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 24 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {MANAGER_COMP/count_b_reg[0]} {MANAGER_COMP/count_b_reg[1]} {MANAGER_COMP/count_b_reg[2]} {MANAGER_COMP/count_b_reg[3]} {MANAGER_COMP/count_b_reg[4]} {MANAGER_COMP/count_b_reg[5]} {MANAGER_COMP/count_b_reg[6]} {MANAGER_COMP/count_b_reg[7]} {MANAGER_COMP/count_b_reg[8]} {MANAGER_COMP/count_b_reg[9]} {MANAGER_COMP/count_b_reg[10]} {MANAGER_COMP/count_b_reg[11]} {MANAGER_COMP/count_b_reg[12]} {MANAGER_COMP/count_b_reg[13]} {MANAGER_COMP/count_b_reg[14]} {MANAGER_COMP/count_b_reg[15]} {MANAGER_COMP/count_b_reg[16]} {MANAGER_COMP/count_b_reg[17]} {MANAGER_COMP/count_b_reg[18]} {MANAGER_COMP/count_b_reg[19]} {MANAGER_COMP/count_b_reg[20]} {MANAGER_COMP/count_b_reg[21]} {MANAGER_COMP/count_b_reg[22]} {MANAGER_COMP/count_b_reg[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 25 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {MANAGER_COMP/delta_reg[0]} {MANAGER_COMP/delta_reg[1]} {MANAGER_COMP/delta_reg[2]} {MANAGER_COMP/delta_reg[3]} {MANAGER_COMP/delta_reg[4]} {MANAGER_COMP/delta_reg[5]} {MANAGER_COMP/delta_reg[6]} {MANAGER_COMP/delta_reg[7]} {MANAGER_COMP/delta_reg[8]} {MANAGER_COMP/delta_reg[9]} {MANAGER_COMP/delta_reg[10]} {MANAGER_COMP/delta_reg[11]} {MANAGER_COMP/delta_reg[12]} {MANAGER_COMP/delta_reg[13]} {MANAGER_COMP/delta_reg[14]} {MANAGER_COMP/delta_reg[15]} {MANAGER_COMP/delta_reg[16]} {MANAGER_COMP/delta_reg[17]} {MANAGER_COMP/delta_reg[18]} {MANAGER_COMP/delta_reg[19]} {MANAGER_COMP/delta_reg[20]} {MANAGER_COMP/delta_reg[21]} {MANAGER_COMP/delta_reg[22]} {MANAGER_COMP/delta_reg[23]} {MANAGER_COMP/delta_reg[24]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 24 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {MANAGER_COMP/count_a_reg[0]} {MANAGER_COMP/count_a_reg[1]} {MANAGER_COMP/count_a_reg[2]} {MANAGER_COMP/count_a_reg[3]} {MANAGER_COMP/count_a_reg[4]} {MANAGER_COMP/count_a_reg[5]} {MANAGER_COMP/count_a_reg[6]} {MANAGER_COMP/count_a_reg[7]} {MANAGER_COMP/count_a_reg[8]} {MANAGER_COMP/count_a_reg[9]} {MANAGER_COMP/count_a_reg[10]} {MANAGER_COMP/count_a_reg[11]} {MANAGER_COMP/count_a_reg[12]} {MANAGER_COMP/count_a_reg[13]} {MANAGER_COMP/count_a_reg[14]} {MANAGER_COMP/count_a_reg[15]} {MANAGER_COMP/count_a_reg[16]} {MANAGER_COMP/count_a_reg[17]} {MANAGER_COMP/count_a_reg[18]} {MANAGER_COMP/count_a_reg[19]} {MANAGER_COMP/count_a_reg[20]} {MANAGER_COMP/count_a_reg[21]} {MANAGER_COMP/count_a_reg[22]} {MANAGER_COMP/count_a_reg[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list MANAGER_COMP/busy_reg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list MANAGER_COMP/done_reg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list MANAGER_COMP/response_reg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list MANAGER_COMP/valid_reg]]
create_debug_core u_ila_signature ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_signature]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_signature]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_signature]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_signature]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_signature]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_signature]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_signature]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_signature]
set_property port_width 1 [get_debug_ports u_ila_signature/clk]
connect_debug_port u_ila_signature/clk [get_nets [list sys_clk_internal_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_signature/probe0]
set_property port_width 120 [get_debug_ports u_ila_signature/probe0]
connect_debug_port u_ila_signature/probe0 [get_nets [list {signature_internal[0]} {signature_internal[1]} {signature_internal[2]} {signature_internal[3]} {signature_internal[4]} {signature_internal[5]} {signature_internal[6]} {signature_internal[7]} {signature_internal[8]} {signature_internal[9]} {signature_internal[10]} {signature_internal[11]} {signature_internal[12]} {signature_internal[13]} {signature_internal[14]} {signature_internal[15]} {signature_internal[16]} {signature_internal[17]} {signature_internal[18]} {signature_internal[19]} {signature_internal[20]} {signature_internal[21]} {signature_internal[22]} {signature_internal[23]} {signature_internal[24]} {signature_internal[25]} {signature_internal[26]} {signature_internal[27]} {signature_internal[28]} {signature_internal[29]} {signature_internal[30]} {signature_internal[31]} {signature_internal[32]} {signature_internal[33]} {signature_internal[34]} {signature_internal[35]} {signature_internal[36]} {signature_internal[37]} {signature_internal[38]} {signature_internal[39]} {signature_internal[40]} {signature_internal[41]} {signature_internal[42]} {signature_internal[43]} {signature_internal[44]} {signature_internal[45]} {signature_internal[46]} {signature_internal[47]} {signature_internal[48]} {signature_internal[49]} {signature_internal[50]} {signature_internal[51]} {signature_internal[52]} {signature_internal[53]} {signature_internal[54]} {signature_internal[55]} {signature_internal[56]} {signature_internal[57]} {signature_internal[58]} {signature_internal[59]} {signature_internal[60]} {signature_internal[61]} {signature_internal[62]} {signature_internal[63]} {signature_internal[64]} {signature_internal[65]} {signature_internal[66]} {signature_internal[67]} {signature_internal[68]} {signature_internal[69]} {signature_internal[70]} {signature_internal[71]} {signature_internal[72]} {signature_internal[73]} {signature_internal[74]} {signature_internal[75]} {signature_internal[76]} {signature_internal[77]} {signature_internal[78]} {signature_internal[79]} {signature_internal[80]} {signature_internal[81]} {signature_internal[82]} {signature_internal[83]} {signature_internal[84]} {signature_internal[85]} {signature_internal[86]} {signature_internal[87]} {signature_internal[88]} {signature_internal[89]} {signature_internal[90]} {signature_internal[91]} {signature_internal[92]} {signature_internal[93]} {signature_internal[94]} {signature_internal[95]} {signature_internal[96]} {signature_internal[97]} {signature_internal[98]} {signature_internal[99]} {signature_internal[100]} {signature_internal[101]} {signature_internal[102]} {signature_internal[103]} {signature_internal[104]} {signature_internal[105]} {signature_internal[106]} {signature_internal[107]} {signature_internal[108]} {signature_internal[109]} {signature_internal[110]} {signature_internal[111]} {signature_internal[112]} {signature_internal[113]} {signature_internal[114]} {signature_internal[115]} {signature_internal[116]} {signature_internal[117]} {signature_internal[118]} {signature_internal[119]}]]
create_debug_port u_ila_signature probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_signature/probe1]
set_property port_width 120 [get_debug_ports u_ila_signature/probe1]
connect_debug_port u_ila_signature/probe1 [get_nets [list {signature_valid_mask[0]} {signature_valid_mask[1]} {signature_valid_mask[2]} {signature_valid_mask[3]} {signature_valid_mask[4]} {signature_valid_mask[5]} {signature_valid_mask[6]} {signature_valid_mask[7]} {signature_valid_mask[8]} {signature_valid_mask[9]} {signature_valid_mask[10]} {signature_valid_mask[11]} {signature_valid_mask[12]} {signature_valid_mask[13]} {signature_valid_mask[14]} {signature_valid_mask[15]} {signature_valid_mask[16]} {signature_valid_mask[17]} {signature_valid_mask[18]} {signature_valid_mask[19]} {signature_valid_mask[20]} {signature_valid_mask[21]} {signature_valid_mask[22]} {signature_valid_mask[23]} {signature_valid_mask[24]} {signature_valid_mask[25]} {signature_valid_mask[26]} {signature_valid_mask[27]} {signature_valid_mask[28]} {signature_valid_mask[29]} {signature_valid_mask[30]} {signature_valid_mask[31]} {signature_valid_mask[32]} {signature_valid_mask[33]} {signature_valid_mask[34]} {signature_valid_mask[35]} {signature_valid_mask[36]} {signature_valid_mask[37]} {signature_valid_mask[38]} {signature_valid_mask[39]} {signature_valid_mask[40]} {signature_valid_mask[41]} {signature_valid_mask[42]} {signature_valid_mask[43]} {signature_valid_mask[44]} {signature_valid_mask[45]} {signature_valid_mask[46]} {signature_valid_mask[47]} {signature_valid_mask[48]} {signature_valid_mask[49]} {signature_valid_mask[50]} {signature_valid_mask[51]} {signature_valid_mask[52]} {signature_valid_mask[53]} {signature_valid_mask[54]} {signature_valid_mask[55]} {signature_valid_mask[56]} {signature_valid_mask[57]} {signature_valid_mask[58]} {signature_valid_mask[59]} {signature_valid_mask[60]} {signature_valid_mask[61]} {signature_valid_mask[62]} {signature_valid_mask[63]} {signature_valid_mask[64]} {signature_valid_mask[65]} {signature_valid_mask[66]} {signature_valid_mask[67]} {signature_valid_mask[68]} {signature_valid_mask[69]} {signature_valid_mask[70]} {signature_valid_mask[71]} {signature_valid_mask[72]} {signature_valid_mask[73]} {signature_valid_mask[74]} {signature_valid_mask[75]} {signature_valid_mask[76]} {signature_valid_mask[77]} {signature_valid_mask[78]} {signature_valid_mask[79]} {signature_valid_mask[80]} {signature_valid_mask[81]} {signature_valid_mask[82]} {signature_valid_mask[83]} {signature_valid_mask[84]} {signature_valid_mask[85]} {signature_valid_mask[86]} {signature_valid_mask[87]} {signature_valid_mask[88]} {signature_valid_mask[89]} {signature_valid_mask[90]} {signature_valid_mask[91]} {signature_valid_mask[92]} {signature_valid_mask[93]} {signature_valid_mask[94]} {signature_valid_mask[95]} {signature_valid_mask[96]} {signature_valid_mask[97]} {signature_valid_mask[98]} {signature_valid_mask[99]} {signature_valid_mask[100]} {signature_valid_mask[101]} {signature_valid_mask[102]} {signature_valid_mask[103]} {signature_valid_mask[104]} {signature_valid_mask[105]} {signature_valid_mask[106]} {signature_valid_mask[107]} {signature_valid_mask[108]} {signature_valid_mask[109]} {signature_valid_mask[110]} {signature_valid_mask[111]} {signature_valid_mask[112]} {signature_valid_mask[113]} {signature_valid_mask[114]} {signature_valid_mask[115]} {signature_valid_mask[116]} {signature_valid_mask[117]} {signature_valid_mask[118]} {signature_valid_mask[119]}]]
create_debug_port u_ila_signature probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_signature/probe2]
set_property port_width 1 [get_debug_ports u_ila_signature/probe2]
connect_debug_port u_ila_signature/probe2 [get_nets [list signature_busy_internal]]
create_debug_port u_ila_signature probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_signature/probe3]
set_property port_width 1 [get_debug_ports u_ila_signature/probe3]
connect_debug_port u_ila_signature/probe3 [get_nets [list signature_ready_internal]]
set_property C_CLK_INPUT_FREQ_HZ 100000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk_internal_BUFG]
