create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys_clk_internal_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 24 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {MANAGER_COMP/count_b_reg[0]} {MANAGER_COMP/count_b_reg[1]} {MANAGER_COMP/count_b_reg[2]} {MANAGER_COMP/count_b_reg[3]} {MANAGER_COMP/count_b_reg[4]} {MANAGER_COMP/count_b_reg[5]} {MANAGER_COMP/count_b_reg[6]} {MANAGER_COMP/count_b_reg[7]} {MANAGER_COMP/count_b_reg[8]} {MANAGER_COMP/count_b_reg[9]} {MANAGER_COMP/count_b_reg[10]} {MANAGER_COMP/count_b_reg[11]} {MANAGER_COMP/count_b_reg[12]} {MANAGER_COMP/count_b_reg[13]} {MANAGER_COMP/count_b_reg[14]} {MANAGER_COMP/count_b_reg[15]} {MANAGER_COMP/count_b_reg[16]} {MANAGER_COMP/count_b_reg[17]} {MANAGER_COMP/count_b_reg[18]} {MANAGER_COMP/count_b_reg[19]} {MANAGER_COMP/count_b_reg[20]} {MANAGER_COMP/count_b_reg[21]} {MANAGER_COMP/count_b_reg[22]} {MANAGER_COMP/count_b_reg[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 25 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {MANAGER_COMP/delta_reg[0]} {MANAGER_COMP/delta_reg[1]} {MANAGER_COMP/delta_reg[2]} {MANAGER_COMP/delta_reg[3]} {MANAGER_COMP/delta_reg[4]} {MANAGER_COMP/delta_reg[5]} {MANAGER_COMP/delta_reg[6]} {MANAGER_COMP/delta_reg[7]} {MANAGER_COMP/delta_reg[8]} {MANAGER_COMP/delta_reg[9]} {MANAGER_COMP/delta_reg[10]} {MANAGER_COMP/delta_reg[11]} {MANAGER_COMP/delta_reg[12]} {MANAGER_COMP/delta_reg[13]} {MANAGER_COMP/delta_reg[14]} {MANAGER_COMP/delta_reg[15]} {MANAGER_COMP/delta_reg[16]} {MANAGER_COMP/delta_reg[17]} {MANAGER_COMP/delta_reg[18]} {MANAGER_COMP/delta_reg[19]} {MANAGER_COMP/delta_reg[20]} {MANAGER_COMP/delta_reg[21]} {MANAGER_COMP/delta_reg[22]} {MANAGER_COMP/delta_reg[23]} {MANAGER_COMP/delta_reg[24]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 24 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {MANAGER_COMP/count_a_reg[0]} {MANAGER_COMP/count_a_reg[1]} {MANAGER_COMP/count_a_reg[2]} {MANAGER_COMP/count_a_reg[3]} {MANAGER_COMP/count_a_reg[4]} {MANAGER_COMP/count_a_reg[5]} {MANAGER_COMP/count_a_reg[6]} {MANAGER_COMP/count_a_reg[7]} {MANAGER_COMP/count_a_reg[8]} {MANAGER_COMP/count_a_reg[9]} {MANAGER_COMP/count_a_reg[10]} {MANAGER_COMP/count_a_reg[11]} {MANAGER_COMP/count_a_reg[12]} {MANAGER_COMP/count_a_reg[13]} {MANAGER_COMP/count_a_reg[14]} {MANAGER_COMP/count_a_reg[15]} {MANAGER_COMP/count_a_reg[16]} {MANAGER_COMP/count_a_reg[17]} {MANAGER_COMP/count_a_reg[18]} {MANAGER_COMP/count_a_reg[19]} {MANAGER_COMP/count_a_reg[20]} {MANAGER_COMP/count_a_reg[21]} {MANAGER_COMP/count_a_reg[22]} {MANAGER_COMP/count_a_reg[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list MANAGER_COMP/busy_reg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list MANAGER_COMP/done_reg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list MANAGER_COMP/response_reg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list MANAGER_COMP/valid_reg]]
set_property C_CLK_INPUT_FREQ_HZ 100000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk_internal_BUFG]
