set_property PACKAGE_PIN AC12 [get_ports PHY0_REFCLK]
set_property PACKAGE_PIN AD12 [get_ports PHY0_CRS_DV]
set_property PACKAGE_PIN AF12 [get_ports {PHY0_RXD[0]}]
set_property PACKAGE_PIN AE15 [get_ports {PHY0_RXD[1]}]
set_property PACKAGE_PIN AF13 [get_ports PHY0_TX_EN]
set_property PACKAGE_PIN AG14 [get_ports {PHY0_TXD[0]}]
set_property PACKAGE_PIN AC11 [get_ports {PHY0_TXD[1]}]

set_property PACKAGE_PIN AE12 [get_ports PHY1_REFCLK]
set_property PACKAGE_PIN AH12 [get_ports PHY1_CRS_DV]
set_property PACKAGE_PIN AH11 [get_ports {PHY1_RXD[0]}]
set_property PACKAGE_PIN AF11 [get_ports {PHY1_RXD[1]}]
set_property PACKAGE_PIN AH10 [get_ports PHY1_TX_EN]
set_property PACKAGE_PIN AG11 [get_ports {PHY1_TXD[0]}]
set_property PACKAGE_PIN AD11 [get_ports {PHY1_TXD[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports PHY0_REFCLK]
set_property IOSTANDARD LVCMOS33 [get_ports PHY0_CRS_DV]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY0_RXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY0_RXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports PHY0_TX_EN]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY0_TXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY0_TXD[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports PHY1_REFCLK]
set_property IOSTANDARD LVCMOS33 [get_ports PHY1_CRS_DV]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY1_RXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY1_RXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports PHY1_TX_EN]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY1_TXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY1_TXD[1]}]

create_clock -name PHY0_REFCLK_50MHZ -period 20.000 [get_ports PHY0_REFCLK]
create_clock -name PHY1_REFCLK_50MHZ -period 20.000 [get_ports PHY1_REFCLK]
