set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[6]}]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[8]}]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[9]}]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[10]}]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[12]}]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[13]}]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[15]}]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[0]}]
set_property MARK_DEBUG true [get_nets PUF_COMP/cnt_en_internal]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[7]}]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[11]}]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[14]}]
set_property MARK_DEBUG true [get_nets PUF_COMP/valid_internal]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[1]}]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[3]}]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[5]}]
set_property MARK_DEBUG true [get_nets PUF_COMP/capture_internal]
set_property MARK_DEBUG true [get_nets PUF_COMP/cnt_rst_internal]
set_property MARK_DEBUG true [get_nets PUF_COMP/response_internal]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[2]}]
set_property MARK_DEBUG true [get_nets {PUF_COMP/ro_en_internal[4]}]
connect_debug_port u_ila_0/probe0 [get_nets [list {PUF_COMP/ro_en_internal[0]} {PUF_COMP/ro_en_internal[1]} {PUF_COMP/ro_en_internal[2]} {PUF_COMP/ro_en_internal[3]} {PUF_COMP/ro_en_internal[4]} {PUF_COMP/ro_en_internal[5]} {PUF_COMP/ro_en_internal[6]} {PUF_COMP/ro_en_internal[7]} {PUF_COMP/ro_en_internal[8]} {PUF_COMP/ro_en_internal[9]} {PUF_COMP/ro_en_internal[10]} {PUF_COMP/ro_en_internal[11]} {PUF_COMP/ro_en_internal[12]} {PUF_COMP/ro_en_internal[13]} {PUF_COMP/ro_en_internal[14]} {PUF_COMP/ro_en_internal[15]}]]


# Preserve PUF measurement values for ILA debugging
set_property MARK_DEBUG true [get_nets -hier -regexp {PUF_COMP/CORE_COMP/count_a_internal\[[0-9]+\]}]
set_property MARK_DEBUG true [get_nets -hier -regexp {PUF_COMP/CORE_COMP/count_b_internal\[[0-9]+\]}]
set_property MARK_DEBUG true [get_nets -hier -regexp {PUF_COMP/delta_internal\[[0-9]+\]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys_clk_internal_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[0].CHANNEL_COMP/ro_en_internal[0]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[1].CHANNEL_COMP/ro_en_internal[1]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[2].CHANNEL_COMP/ro_en_internal[2]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[3].CHANNEL_COMP/ro_en_internal[3]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[4].CHANNEL_COMP/ro_en_internal[4]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[5].CHANNEL_COMP/ro_en_internal[5]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[6].CHANNEL_COMP/ro_en_internal[6]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[7].CHANNEL_COMP/ro_en_internal[7]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[8].CHANNEL_COMP/ro_en_internal[8]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[9].CHANNEL_COMP/ro_en_internal[9]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[10].CHANNEL_COMP/ro_en_internal[10]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[11].CHANNEL_COMP/ro_en_internal[11]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[12].CHANNEL_COMP/ro_en_internal[12]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[13].CHANNEL_COMP/ro_en_internal[13]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[14].CHANNEL_COMP/ro_en_internal[14]} {PUF_COMP/CORE_COMP/BANK_COMP/GEN_CHANNELS[15].CHANNEL_COMP/ro_en_internal[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list PUF_COMP/capture_internal]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list PUF_COMP/cnt_en_internal]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list PUF_COMP/cnt_rst_internal]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list PUF_COMP/response_internal]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list PUF_COMP/valid_internal]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 24 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {PUF_COMP/CORE_COMP/count_a_internal[0]} {PUF_COMP/CORE_COMP/count_a_internal[1]} {PUF_COMP/CORE_COMP/count_a_internal[2]} {PUF_COMP/CORE_COMP/count_a_internal[3]} {PUF_COMP/CORE_COMP/count_a_internal[4]} {PUF_COMP/CORE_COMP/count_a_internal[5]} {PUF_COMP/CORE_COMP/count_a_internal[6]} {PUF_COMP/CORE_COMP/count_a_internal[7]} {PUF_COMP/CORE_COMP/count_a_internal[8]} {PUF_COMP/CORE_COMP/count_a_internal[9]} {PUF_COMP/CORE_COMP/count_a_internal[10]} {PUF_COMP/CORE_COMP/count_a_internal[11]} {PUF_COMP/CORE_COMP/count_a_internal[12]} {PUF_COMP/CORE_COMP/count_a_internal[13]} {PUF_COMP/CORE_COMP/count_a_internal[14]} {PUF_COMP/CORE_COMP/count_a_internal[15]} {PUF_COMP/CORE_COMP/count_a_internal[16]} {PUF_COMP/CORE_COMP/count_a_internal[17]} {PUF_COMP/CORE_COMP/count_a_internal[18]} {PUF_COMP/CORE_COMP/count_a_internal[19]} {PUF_COMP/CORE_COMP/count_a_internal[20]} {PUF_COMP/CORE_COMP/count_a_internal[21]} {PUF_COMP/CORE_COMP/count_a_internal[22]} {PUF_COMP/CORE_COMP/count_a_internal[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 24 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {PUF_COMP/CORE_COMP/count_b_internal[0]} {PUF_COMP/CORE_COMP/count_b_internal[1]} {PUF_COMP/CORE_COMP/count_b_internal[2]} {PUF_COMP/CORE_COMP/count_b_internal[3]} {PUF_COMP/CORE_COMP/count_b_internal[4]} {PUF_COMP/CORE_COMP/count_b_internal[5]} {PUF_COMP/CORE_COMP/count_b_internal[6]} {PUF_COMP/CORE_COMP/count_b_internal[7]} {PUF_COMP/CORE_COMP/count_b_internal[8]} {PUF_COMP/CORE_COMP/count_b_internal[9]} {PUF_COMP/CORE_COMP/count_b_internal[10]} {PUF_COMP/CORE_COMP/count_b_internal[11]} {PUF_COMP/CORE_COMP/count_b_internal[12]} {PUF_COMP/CORE_COMP/count_b_internal[13]} {PUF_COMP/CORE_COMP/count_b_internal[14]} {PUF_COMP/CORE_COMP/count_b_internal[15]} {PUF_COMP/CORE_COMP/count_b_internal[16]} {PUF_COMP/CORE_COMP/count_b_internal[17]} {PUF_COMP/CORE_COMP/count_b_internal[18]} {PUF_COMP/CORE_COMP/count_b_internal[19]} {PUF_COMP/CORE_COMP/count_b_internal[20]} {PUF_COMP/CORE_COMP/count_b_internal[21]} {PUF_COMP/CORE_COMP/count_b_internal[22]} {PUF_COMP/CORE_COMP/count_b_internal[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 25 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {PUF_COMP/delta_internal[0]} {PUF_COMP/delta_internal[1]} {PUF_COMP/delta_internal[2]} {PUF_COMP/delta_internal[3]} {PUF_COMP/delta_internal[4]} {PUF_COMP/delta_internal[5]} {PUF_COMP/delta_internal[6]} {PUF_COMP/delta_internal[7]} {PUF_COMP/delta_internal[8]} {PUF_COMP/delta_internal[9]} {PUF_COMP/delta_internal[10]} {PUF_COMP/delta_internal[11]} {PUF_COMP/delta_internal[12]} {PUF_COMP/delta_internal[13]} {PUF_COMP/delta_internal[14]} {PUF_COMP/delta_internal[15]} {PUF_COMP/delta_internal[16]} {PUF_COMP/delta_internal[17]} {PUF_COMP/delta_internal[18]} {PUF_COMP/delta_internal[19]} {PUF_COMP/delta_internal[20]} {PUF_COMP/delta_internal[21]} {PUF_COMP/delta_internal[22]} {PUF_COMP/delta_internal[23]} {PUF_COMP/delta_internal[24]}]]
set_property C_CLK_INPUT_FREQ_HZ 100000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk_internal_BUFG]
